theme: jekyll-theme-Minimal
title: Pouria Saidi
description: Nothing for Now.
markdown: kramdown
highlighter: rouge
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page. (true or false)
heading_anchors: true

# Activate a "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"

